#
# Description:
# ------------
#
# This is a small test case that creates an enterprise manager with its database,
# a webview and a small sample EPAgent that sends data (to verify that the
# setup is valid)
#

em:
  image: apm-em:10.3
  links:
    - db:db
  ports:
    - "5001:5001"
    - "8081:8081"
  environment:
    - HEAP="2048m"
  volumes:
    # management module location
    - ~/mm:/root/Introscope/config/modules

db:
  image: apm-postgres:10.3

webview:
  image: apm-webview:10.3
  links:
    - em:em
  ports:
    - "8080:8080"

sample:
  image: apm-sample:9.7
  links:
    - em:em
